---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Mobility ATT Connector"
host: "localhost:10010"
basePath: "/"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /getTaxiCurrentGps:
    get:
      description: "Returns current gps of taxis"
      operationId: "getTaxiCurrentGps"
      parameters: []
      responses:
        200:
          description: "Success"
      x-swagger-router-controller: "Default"
    x-swagger-router-controller: "taxi_service"
  /getTaxiByLocation:
    get:
      description: "Returns taxi 500 m around the location"
      operationId: "getTaxiByLocation"
      parameters:
      - name: "name"
        in: "query"
        description: "The name of the place"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
      x-swagger-router-controller: "Default"
    x-swagger-router-controller: "taxi_service"
  /swagger:
    x-swagger-pipe: "swagger_raw"
definitions: {}
